name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
        
