name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ybcmd56FVvrpTBuGm5khGoCA8ae0/jRJAAn8jjA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VNQzSLatFMFAsI57kgeXcVMY6QQY/ySwFWPCIqP
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_fODeqysItaBDNsSGxAASfZwwYdwt/nRNpp5LgDA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ybcmd56FVvrpTBuGm5khGoCA8ae0/jRJAAn8jjA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VNQzSLatFMFAsI57kgeXcVMY6QQY/ySwFWPCIqP
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_fODeqysItaBDNsSGxAASfZwwYdwt/nRNpp5LgDA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ybcmd56FVvrpTBuGm5khGoCA8ae0/jRJAAn8jjA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VNQzSLatFMFAsI57kgeXcVMY6QQY/ySwFWPCIqP
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_fODeqysItaBDNsSGxAASfZwwYdwt/nRNpp5LgDA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ybcmd56FVvrpTBuGm5khGoCA8ae0/jRJAAn8jjA
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VNQzSLatFMFAsI57kgeXcVMY6QQY/ySwFWPCIqP
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_fODeqysItaBDNsSGxAASfZwwYdwt/nRNpp5LgDA
